# Generated by Django 5.2.14 on 2026-05-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardprinting'),
        ('collection', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('light_played', 'Light Played'), ('played', 'Played'), ('poor', 'Poor')], max_length=16)),
                ('edition', models.CharField(choices=[('first', '1st Edition'), ('unlimited', 'Unlimited'), ('limited', 'Limited')], max_length=16)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean')], max_length=8)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='portfolio.portfolio')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='cards.cardprinting')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='collection.storagelocation')),
            ],
            options={
                'ordering': ['portfolio', 'printing'],
                'constraints': [models.UniqueConstraint(fields=('printing', 'condition', 'edition', 'language', 'portfolio'), name='unique_collection_item_natural_key'), models.CheckConstraint(condition=models.Q(('condition__in', ['mint', 'near_mint', 'excellent', 'good', 'light_played', 'played', 'poor'])), name='collection_item_condition_valid'), models.CheckConstraint(condition=models.Q(('edition__in', ['first', 'unlimited', 'limited'])), name='collection_item_edition_valid'), models.CheckConstraint(condition=models.Q(('language__in', ['en', 'fr', 'de', 'it', 'es', 'pt', 'ja', 'ko'])), name='collection_item_language_valid')],
            },
        ),
    ]
