# Generated by Django 5.2.14 on 2026-05-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('import_source_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='collection.collectionitem')),
            ],
            options={
                'ordering': ['collection_item', models.OrderBy(models.F('acquired_at'), nulls_last=True), 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='collection_lot_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='collection_lot_unit_cost_non_negative')],
            },
        ),
    ]
