# Generated by Django 5.2.14 on 2026-05-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collectionlot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionlot',
            constraint=models.UniqueConstraint(fields=('collection_item', 'import_source_ref'), name='unique_lot_per_collection_item_import_source_ref'),
        ),
    ]
