# Generated by Django 5.2.14 on 2026-05-21 23:28

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_code', models.CharField(db_index=True, max_length=32)),
                ('set_rarity', models.CharField(max_length=64)),
                ('variant_label', models.CharField(blank=True, max_length=128, null=True)),
                ('set_name', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='cards.card')),
            ],
            options={
                'ordering': ['set_code', 'set_rarity'],
                'constraints': [models.UniqueConstraint(fields=('card', 'set_code', 'set_rarity', 'variant_label'), name='unique_card_printing_natural_key', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('variant_label__isnull', True), models.Q(('variant_label', django.db.models.functions.text.Trim('variant_label')), models.Q(('variant_label', ''), _negated=True)), _connector='OR'), name='card_printing_variant_label_canonical')],
            },
        ),
    ]
