# Generated by Django 5.2.14 on 2026-05-24 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardprinting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('ygoprodeck', 'YGOPRODeck')], max_length=32)),
                ('set_code', models.CharField(db_index=True, max_length=32)),
                ('set_rarity', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_aliases', to='cards.card')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='cards.cardprinting')),
            ],
            options={
                'ordering': ['source', 'set_code', 'set_rarity'],
                'constraints': [models.UniqueConstraint(fields=('source', 'card', 'set_code', 'set_rarity'), name='unique_printing_alias_provisional_key'), models.CheckConstraint(condition=models.Q(('source__in', ['ygoprodeck'])), name='printing_alias_source_valid')],
            },
        ),
    ]
