# Generated by Django 5.2.14 on 2026-05-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_printingalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprinting',
            name='is_multi_variant',
            field=models.BooleanField(default=False),
        ),
    ]
