# Generated by Django 5.2.14 on 2026-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardprinting_is_multi_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archetype',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
