import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `@hey-api/openapi-ts` (Phase 4 slice 2). The output is
    // consumed, not hand-edited; linting it is noise (the generator's own
    // conventions don't always match ours).
    "src/lib/api/generated/**",
  ]),
]);

export default eslintConfig;
