# Generated by Django 5.2.14 on 2026-05-22 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_cardprinting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPriceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('tcgcsv', 'TCGCSV')], max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('printing', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='external_price_ids', to='cards.cardprinting')),
            ],
            options={
                'ordering': ['provider', 'external_id'],
                'indexes': [models.Index(fields=['printing', 'provider'], name='epi_printing_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_external_price_id_per_provider')],
            },
        ),
    ]
