# Generated by Django 5.2.14 on 2026-05-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardprinting'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.CharField(choices=[('first', '1st Edition'), ('unlimited', 'Unlimited'), ('limited', 'Limited')], max_length=16)),
                ('source', models.CharField(choices=[('tcgcsv', 'TCGCSV')], max_length=32)),
                ('snapshot_date', models.DateField()),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direct_low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_subtype_name', models.CharField(blank=True, max_length=64, null=True)),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='cards.cardprinting')),
            ],
            options={
                'ordering': ['printing', 'edition', '-snapshot_date', 'source'],
                'indexes': [models.Index(fields=['printing', 'edition', '-snapshot_date'], name='price_snapshot_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('printing', 'edition', 'source', 'snapshot_date'), name='unique_price_snapshot_natural_key'), models.CheckConstraint(condition=models.Q(('edition__in', ['first', 'unlimited', 'limited'])), name='price_snapshot_edition_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['tcgcsv'])), name='price_snapshot_source_valid')],
            },
        ),
    ]
