# Generated by Django 5.2.14 on 2026-05-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('tcgcsv', 'TCGCSV')], max_length=32)),
                ('external_id', models.CharField(max_length=64)),
                ('set_code', models.CharField(db_index=True, max_length=32)),
                ('set_rarity', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('set_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('no_printing_match', 'No printing match'), ('multi_variant', 'Multiple variants'), ('rarity_disagreement', 'Rarity disagreement'), ('external_id_conflict', 'External id conflict')], max_length=32)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='unresolved', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['provider', 'status', 'set_code', 'set_rarity'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_unmatched_product_per_provider'), models.CheckConstraint(condition=models.Q(('provider__in', ['tcgcsv'])), name='unmatched_product_provider_valid'), models.CheckConstraint(condition=models.Q(('reason__in', ['no_printing_match', 'multi_variant', 'rarity_disagreement', 'external_id_conflict'])), name='unmatched_product_reason_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['unresolved', 'resolved', 'ignored'])), name='unmatched_product_status_valid')],
            },
        ),
    ]
