# Generated by Django 5.2.14 on 2026-05-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_printingalias'),
        ('pricing', '0003_unmatchedproduct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('low_price__isnull', True), ('low_price__gte', 0), _connector='OR'), models.Q(('mid_price__isnull', True), ('mid_price__gte', 0), _connector='OR'), models.Q(('high_price__isnull', True), ('high_price__gte', 0), _connector='OR'), models.Q(('market_price__isnull', True), ('market_price__gte', 0), _connector='OR'), models.Q(('direct_low_price__isnull', True), ('direct_low_price__gte', 0), _connector='OR')), name='price_snapshot_prices_non_negative'),
        ),
    ]
