# Generated by Django 5.2.14 on 2026-05-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_archetype'),
        ('pricing', '0004_pricesnapshot_price_snapshot_prices_non_negative'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['source', '-snapshot_date', 'printing', 'edition'], name='price_snapshot_movers_idx'),
        ),
    ]
