# Generated by Django 5.2.14 on 2026-05-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_card_archetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('threshold_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('window_days', models.PositiveSmallIntegerField(choices=[(7, '7 days'), (30, '30 days'), (90, '90 days')], default=30)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('any', 'Any direction')], default='any', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_pct__gt', 0)), name='alert_rule_threshold_positive'), models.CheckConstraint(condition=models.Q(('direction__in', ['up', 'down', 'any'])), name='alert_rule_direction_valid'), models.CheckConstraint(condition=models.Q(('window_days__in', [7, 30, 90])), name='alert_rule_window_valid')],
            },
        ),
        migrations.CreateModel(
            name='AlertRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('rules_evaluated', models.PositiveIntegerField(blank=True, null=True)),
                ('events_created', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='alert_run_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['success', 'failed', 'skipped'])), name='alert_run_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.CharField(choices=[('first', '1st Edition'), ('unlimited', 'Unlimited'), ('limited', 'Limited')], max_length=16)),
                ('triggered_on', models.DateField()),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_threshold_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rule_window_days', models.PositiveSmallIntegerField()),
                ('rule_direction', models.CharField(max_length=8)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pct_change', models.DecimalField(decimal_places=2, max_digits=16)),
                ('dollar_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_events', to='cards.cardprinting')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_on', '-id'],
                'indexes': [models.Index(fields=['-triggered_on', '-id'], name='alert_event_feed_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule', 'printing', 'edition', 'triggered_on'), name='unique_alert_event_per_rule_pair_day'), models.CheckConstraint(condition=models.Q(('edition__in', ['first', 'unlimited', 'limited'])), name='alert_event_edition_valid'), models.CheckConstraint(condition=models.Q(('start_price__gte', 0)), name='alert_event_start_price_non_negative'), models.CheckConstraint(condition=models.Q(('end_price__gte', 0)), name='alert_event_end_price_non_negative')],
            },
        ),
    ]
