# Generated by Django 5.2.14 on 2026-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ygoprodeck_metadata', 'YGOPRODeck metadata'), ('tcgcsv_pricing', 'TCGCSV pricing')], max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('card_count', models.PositiveIntegerField(blank=True, null=True)),
                ('printing_count', models.PositiveIntegerField(blank=True, null=True)),
                ('product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('price_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['kind', '-created_at', '-id'],
                'indexes': [models.Index(fields=['kind', 'status', '-created_at'], name='sync_run_latest_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['ygoprodeck_metadata', 'tcgcsv_pricing'])), name='sync_run_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['success', 'failed'])), name='sync_run_status_valid')],
            },
        ),
    ]
