# Generated by Django 5.2.14 on 2026-05-23 06:33

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('liquidation_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unrealized_gain', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valuation_method', models.CharField(max_length=64)),
                ('valuation_version', models.PositiveSmallIntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['portfolio', '-snapshot_date'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'snapshot_date'), name='unique_portfolio_value_snapshot_per_day'), models.CheckConstraint(condition=models.Q(('market_value__gte', 0)), name='portfolio_value_snapshot_market_value_non_negative'), models.CheckConstraint(condition=models.Q(('liquidation_value__gte', 0)), name='portfolio_value_snapshot_liquidation_value_non_negative'), models.CheckConstraint(condition=models.Q(('cost_basis__gte', 0)), name='portfolio_value_snapshot_cost_basis_non_negative'), models.CheckConstraint(condition=models.Q(('unrealized_gain', django.db.models.expressions.CombinedExpression(models.F('market_value'), '-', models.F('cost_basis')))), name='portfolio_value_snapshot_unrealized_gain_matches')],
            },
        ),
    ]
