# Generated by Django 5.2.14 on 2026-05-25 20:15

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliovaluesnapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfoliovaluesnapshot',
            name='portfolio_value_snapshot_unrealized_gain_matches',
        ),
        migrations.AddField(
            model_name='portfoliovaluesnapshot',
            name='costed_card_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliovaluesnapshot',
            name='priced_card_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliovaluesnapshot',
            name='total_card_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliovaluesnapshot',
            name='unrealized_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='portfoliovaluesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('priced_card_count__lte', models.F('total_card_count'))), name='portfolio_value_snapshot_priced_count_within_total'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovaluesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('costed_card_count__lte', models.F('total_card_count'))), name='portfolio_value_snapshot_costed_count_within_total'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovaluesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('unrealized_gain__isnull', True), ('unrealized_gain', django.db.models.expressions.CombinedExpression(models.F('market_value'), '-', models.F('cost_basis'))), _connector='OR'), name='portfolio_value_snapshot_unrealized_gain_matches'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovaluesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('costed_card_count', models.F('total_card_count')), ('priced_card_count', models.F('total_card_count')), ('unrealized_gain__isnull', False)), models.Q(models.Q(('priced_card_count', models.F('total_card_count')), ('costed_card_count', models.F('total_card_count')), _negated=True), ('unrealized_gain__isnull', True)), _connector='OR'), name='portfolio_value_snapshot_gain_iff_complete'),
        ),
    ]
