# Generated by Django 5.2.14 on 2026-06-28 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('demo', 'Demo'), ('user', 'User')], default='anonymous', max_length=16)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('session_key_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('view_name', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('object_type', models.CharField(blank=True, default='', max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='audit_event_recent_idx'), models.Index(fields=['actor', '-created_at'], name='audit_event_actor_idx'), models.Index(fields=['status_code', '-created_at'], name='audit_event_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], max_length=16)),
                ('actor_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('demo', 'Demo'), ('user', 'User')], default='anonymous', max_length=16)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('session_key_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(blank=True, default='error', max_length=16)),
                ('exception_class', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=512)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['fingerprint', '-created_at'], name='error_log_fingerprint_idx'), models.Index(fields=['source', '-created_at'], name='error_log_source_idx'), models.Index(fields=['-created_at', '-id'], name='error_log_recent_idx')],
            },
        ),
    ]
