# Generated by Django 5.2.14 on 2026-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_percent', models.FloatField()),
                ('load_1m', models.FloatField()),
                ('mem_used_mb', models.PositiveIntegerField()),
                ('mem_total_mb', models.PositiveIntegerField()),
                ('disk_used_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('net_rx_bytes', models.BigIntegerField()),
                ('net_tx_bytes', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='host_metric_recent_idx')],
            },
        ),
    ]
