# Generated by Django 5.2.14 on 2026-05-31 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0004_collectionlot_unique_lot_per_collection_item_import_source_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeckMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_memberships', to='collection.collectionitem')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='decks.deck')),
            ],
            options={
                'ordering': ['deck', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deck', 'collection_item'), name='unique_deck_membership')],
            },
        ),
    ]
