# Generated by Django 5.2.14 on 2026-05-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('portfolios_seen', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshots_created', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshots_existing', models.PositiveIntegerField(blank=True, null=True)),
                ('holdings_valued', models.PositiveIntegerField(blank=True, null=True)),
                ('holdings_unpriced', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='valuation_run_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['success', 'failed', 'skipped'])), name='valuation_run_status_valid')],
            },
        ),
    ]
