# Generated by Django 5.2.14 on 2026-05-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0003_printingalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_format', models.CharField(choices=[('dragon_shield', 'Dragon Shield')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_format__in', ['dragon_shield'])), name='import_batch_source_format_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'review', 'completed', 'failed'])), name='import_batch_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('normalized_data', models.JSONField(blank=True, null=True)),
                ('match_confidence', models.CharField(choices=[('exact', 'Exact'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unmatched', 'Unmatched')], default='unmatched', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('materialized', 'Materialized'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
                ('matched_printing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='cards.cardprinting')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'status'], name='import_row_batch_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_import_row_per_batch'), models.CheckConstraint(condition=models.Q(('match_confidence__in', ['exact', 'high', 'medium', 'low', 'unmatched'])), name='import_row_match_confidence_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'materialized', 'skipped', 'error'])), name='import_row_status_valid')],
            },
        ),
    ]
